export const CONFIG = {
  TARGET_FPS: 120,
  MAX_DT: 1 / 30,
  WORLD_FADE_ALPHA: 0.48,
  PLAYER: {
    SPEED: 238,
    TURN_SPEED: 4.2,
    RADIUS: 10,
    TRAIL_INTERVAL: 0.018,
    TRAIL_LENGTH: 11,
    SPEED_MULTIPLIER_FAST: 1.4,
  },
  MISSILE: {
    BASE_SPEED: 243,
    SPEED_GROWTH_PER_SEC: 3.2,
    BASE_TURN_RATE: 2.8,
    TURN_GROWTH_PER_SEC: 0.04,
    RADIUS: 8,
    TRAIL_INTERVAL: 0.024,
     TRAIL_LENGTH: 17,
  },
  SPAWNER: {
    START_INTERVAL: 1.4,
    MIN_INTERVAL: 0.4,
    RAMP_PER_SEC: 0.032,
    OFFSCREEN_MARGIN: 110,
  },
  DIFFICULTY: {
    MISSILE_CAP_START: 3,
    MISSILE_CAP_GROWTH: 0.084,
    MISSILE_CAP_MAX: 24,
  },
  SCORING: {
    SURVIVAL_PER_SEC: 12,
    DESTROY_BONUS: 60,
    STAR_BONUS: 100,
    NEAR_MISS_BONUS: 25,
    NEAR_MISS_DISTANCE: 56,
    NEAR_MISS_COOLDOWN: 0.5,
  },
  STARS: {
    MAX_ACTIVE: 3,
    SPAWN_INTERVAL: 2.5,
    RADIUS: 17,
    DESPAWN_DISTANCE: 720,
  },
  PARTICLES: {
    POOL_SIZE: 1400,
    EXPLOSION_COUNT: 28,
    MISSILE_COLLISION_COUNT: 16,
  },
  CAMERA: {
    TRAUMA_DECAY: 0,
    MAX_SHAKE: 0,
  },
  MODES: {
    normal: {
      label: "NORMAL",
      missileSpeedMultiplier: 1,
      spawnRateMultiplier: 1,
      scoreMultiplier: 1,
      missileCapMultiplier: 1,
      playerSpeedMultiplier: 1,
    },
    fast: {
      label: "FAST",
      missileSpeedMultiplier: 1.3,
      spawnRateMultiplier: 1.8,
      scoreMultiplier: 2.0, 
      missileCapMultiplier: 2,
      playerSpeedMultiplier: 1.5,
    },
  },
  PLANES: [
     { label: "WHITE", body: "#ffffff", glow: "rgba(232,244,255,0.2)", wing: "#d7e6ff" },
     { label: "RED", body: "#ff4d4d", glow: "rgba(255,102,102,0.2)", wing: "#ffd0d0" },
     { label: "GOLD", body: "#ffb11c", glow: "rgba(255,196,85,0.2)", wing: "#ffe0a2" },
     { label: "STEALTH", body: "#6f6767", glow: "rgba(193,174,174,0.15)", wing: "#afa0a0" },
  ],
};
